components/app_component/config/routes.rb
AppComponent::Engine.routes.draw do
  resources :games
  resources :teams
  root to: 'welcome#index'
end

components/app_component/app/models/app_component/application_record.rb
module AppComponent
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

components/app_component/app/models/app_component/game.rb
module AppComponent
  class Game < ApplicationRecord
  end
end

components/app_component/app/models/app_component/team.rb
module AppComponent
  class Team < ApplicationRecord
  end
end

components/app_component/app/controllers/app_component/application_controller.rb
module AppComponent
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

components/app_component/app/controllers/app_component/games_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class GamesController < ApplicationController
    before_action :set_game, only: [:show, :edit, :update, :destroy]

    # GET /games
    def index
      @games = Game.all
    end

    # GET /games/1
    def show
    end

    # GET /games/new
    def new
      @game = Game.new
    end

    # GET /games/1/edit
    def edit
    end

    # POST /games
    def create
      @game = Game.new(game_params)

      if @game.save
        redirect_to @game, notice: 'Game was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /games/1
    def update
      if @game.update(game_params)
        redirect_to @game, notice: 'Game was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /games/1
    def destroy
      @game.destroy
      redirect_to games_url, notice: 'Game was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_game
        @game = Game.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def game_params
        params.require(:game).permit(:date, : location)
      end
  end
end

components/app_component/app/controllers/app_component/teams_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class TeamsController < ApplicationController
    before_action :set_team, only: [:show, :edit, :update, :destroy]

    # GET /teams
    def index
      @teams = Team.all
    end

    # GET /teams/1
    def show
    end

    # GET /teams/new
    def new
      @team = Team.new
    end

    # GET /teams/1/edit
    def edit
    end

    # POST /teams
    def create
      @team = Team.new(team_params)

      if @team.save
        redirect_to @team, notice: 'Team was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /teams/1
    def update
      if @team.update(team_params)
        redirect_to @team, notice: 'Team was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /teams/1
    def destroy
      @team.destroy
      redirect_to teams_url, notice: 'Team was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_team
        @team = Team.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def team_params
        params.require(:team).permit(:name)
      end
  end
end

components/app_component/app/controllers/app_component/welcome_controller.rb
require_dependency "app_component/application_controller"

module AppComponent
  class WelcomeController < ApplicationController
    def index
    end
  end
end

components/app_component/app/helpers/app_component/application_helper.rb
module AppComponent
  module ApplicationHelper
  end
end

components/app_component/app/helpers/app_component/games_helper.rb
module AppComponent
  module GamesHelper
  end
end

components/app_component/app/helpers/app_component/teams_helper.rb
module AppComponent
  module TeamsHelper
  end
end

components/app_component/app/helpers/app_component/welcome_helper.rb
module AppComponent
  module WelcomeHelper
  end
end

components/app_component/app/views/app_component/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label : location %>
    <%= form.text_field : location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/app_component/app/views/app_component/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th> location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.date %></td>
        <td><%= game. location %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

components/app_component/app/views/app_component/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @game.date %>
</p>

<p>
  <strong> location:</strong>
  <%= @game. location %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

components/app_component/app/views/app_component/teams/_form.html.erb
<%= form_with(model: team, local: true) do |form| %>
  <% if team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
      <% team.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

components/app_component/app/views/app_component/teams/edit.html.erb
<h1>Editing Team</h1>

<%= render 'form', team: @team %>

<%= link_to 'Show', @team %> |
<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.name %></td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_team_path %>

components/app_component/app/views/app_component/teams/new.html.erb
<h1>New Team</h1>

<%= render 'form', team: @team %>

<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team.name %>
</p>

<%= link_to 'Edit', edit_team_path(@team) %> |
<%= link_to 'Back', teams_path %>

components/app_component/app/views/app_component/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/app_component/welcome/index.html.erb</p>

components/app_component/app/views/layouts/app_component/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App component</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "app_component/application", media: "all" %>
  <%= javascript_include_tag "app_component/application" %>
</head>
<body>

<%= yield %>

</body>
</html>